### ISSUE TITLE
会崩

### ISSUE THREAD

**Issue by walking-sun** [yate1996/KLine#11]
切换线图的时候有时候会崩掉。。

**Comment by walking-sun** [comment]
崩溃应该是drawrect重绘使内存激增。建议在画大量k线时，使用图层。------------------ 原始邮件 ------------------
发件人: "WillkYang"<notifications@github.com>
发送时间: 2020年3月31日(星期二) 晚上11:19
收件人: "WillkYang/Y_KLine"<Y_KLine@noreply.github.com>;
抄送: "walking-sun"<1143597065@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [WillkYang/Y_KLine] 会崩 (#11)




 
Closed #11.
 
&mdash;

**Comment by WillkYang** [comment]
已修复
