### ISSUE TITLE
我想接入你这个k线图

### ISSUE THREAD

**Issue by zw11223344** [yate1996/KLine#17]
我看了好几天，不是很清楚你的数据从那个加载进去的。我应该在哪儿切换数据～

**Comment by rockmanzzx** [comment]
在几个plist文件里

**Comment by zw11223344** [comment]
plist里面解决不了吧，还有一个问题，分时图的时间轴好像不对。都找不到在哪儿修改的～

**Comment by WillkYang** [comment]
数据源的提供属于业务代码，需要自行实现，demo中在Y_StockChartViewController.m文件中实现使用接口获取数据源的例子。
