### ISSUE TITLE
感觉MA线的计算稍有问题，画不全，看了下算法没问题

### ISSUE THREAD

**Issue by liuyingjieyeah** [yate1996/KLine#2]
求解决或指导

**Comment by WillkYang** [comment]
你是说一开始的地方吗？因为MA7是7天均值，所以我是从第七天开始画线的，而MA30则是从第30天开始画的哟

**Comment by liuyingjieyeah** [comment]
恩，我知道，但是我这边要求跟同花顺一样绘制5/10/20/30的MA曲线，而且是从同一X坐标开始，我在考虑如何做到呢。

**Comment by liuyingjieyeah** [comment]
已解决，但也不算解决。那种效果只能以增加取值范围来处理...
