### ISSUE TITLE
您好，在看您的demo过程中有一些疑惑，希望有时间解答一下。

### ISSUE THREAD

**Issue by Leo007Lee** [yate1996/KLine#20]
Y_KLineMainView.m 中，maxAssert *= 1.0001; minAssert *= 0.9991; 这两个变量为什么要这样处理，这样处理会不会有偏差呢？期待您的答案，蟹蟹~ 
PS：您的demo写得挺不错的，很有收获

**Comment by Leo007Lee** [comment]
另外，scrollView的contentSize计算得貌似不太准确

**Comment by bigNiuSanMao** [comment]
楼上 知道为什么了 也做到这块了 搞不清为什么？ 希望作者解答一下

**Comment by WillkYang** [comment]
maxAssert *= 1.0001; minAssert *= 0.9991;
是为了在顶部和底部留出一点空间，也可以不写的

**Comment by bigNiuSanMao** [comment]
@WillkYang  我还以为 这个 maxAssert *= 1.0001; minAssert *= 0.9991;  是处理 最大值最小值相等时，分母为0 的操作
