### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by 18423671461** [yate1996/KLine#24]
请问有Android的deom

**Comment by WillkYang** [comment]
安卓我不熟悉呢，要不你看看源码，然后翻译一个安卓版本的如何😄

**Comment by 18423671461** [comment]
嗯，可以尽量去尝试下，ios的我也不懂

在 2018-03-30 00:02:38，"WillkYang" <notifications@github.com> 写道：


安卓我不熟悉呢，要不你看看源码，然后翻译一个安卓版本的如何😄
