### ISSUE TITLE
K显示有问题

### ISSUE THREAD

**Issue by hxx1197411446** [yate1996/KLine#26]
![0d47c0c0-5f3c-9570-c808-ecef6b9660b7](https://user-images.githubusercontent.com/10133519/35469380-6ef539b6-036e-11e8-90c5-5b8bf6878cff.png)

**Comment by WillkYang** [comment]
可以看看数据源的参数传入是否正确，例如最高价，最低价这些。

![img_3847](https://user-images.githubusercontent.com/10380145/38099434-2b046bae-33ad-11e8-83c4-23d01f63641c.PNG)
