### ISSUE TITLE
新的数据接口K线图展示的时间数据是反的

### ISSUE THREAD

**Issue by SunYanpeng2017** [yate1996/KLine#30]
![11111111111111](https://user-images.githubusercontent.com/34431901/36962581-1a73e646-208b-11e8-81f4-d744d7d96f6b.jpeg)

**Comment by achongGitHub** [comment]
你好   现在这个框架数据返回不回来了   请问一下你当时看到的数据格式什么样的啊   方便加个好友请教一下吗

**Comment by renjiale1214** [comment]
不光是时间，你把你获取到的数据自己sort一下，倒序一下就OK了，不过需要注意如果你开了ws，替换和新加数据时别弄错了
