### ISSUE TITLE
WebSocket添加K线数据

### ISSUE THREAD

**Issue by renjiale1214** [yate1996/KLine#35]
第一次http请求到整组数据后，如果后边推来一条一条的数据，想问一下作者如果要做的话怎么去考虑这个实现呢？我目前在自己写，1min的好写，已经处理好了

**Comment by maxlxq** [comment]
同问+1

**Comment by renjiale1214** [comment]
我做完了，根据时间去判断websocket收到的数据的时间戳，和当前GlobalModel里的数据最后一条去对比，如果应该是刷新的，就替换最后一条数据，如果是要添加新数据，就在最后再加一条，然后调用setNeedDisplay去刷新就可以了。需要注意的是根据你请求的K线时间不同，1min的，30min的这些判断方式是不一样的，每一种K线都有一个判断逻辑，1week的比较麻烦，我简化了判断直接判7天，后台每根周线的时间戳都是周一的0点0分，所以好判断很多

**Comment by Mayxueyin** [comment]
使用socket之后遇到两个问题,1.添加数据后刷新,回到了最右边状态. 2.KDJ模式下socket拼接的心数据,kdj值都为0,获取不到新的值,请问这两个该怎么解决呢.

**Comment by 19940524** [comment]
> 使用socket之后遇到两个问题,1.添加数据后刷新,回到了最右边状态. 2.KDJ模式下socket拼接的心数据,kdj值都为0,获取不到新的值,请问这两个该怎么解决呢.

添加数据后刷新,回到了最右边状态,这个问题请教下，解决没有

**Comment by qingyongone** [comment]
怎么弄的你们弄好了吗
