### ISSUE TITLE
K线高度显示问题

### ISSUE THREAD

**Issue by renjiale1214** [yate1996/KLine#37]
最近调数据发现问题，如果数据特别大的时候，所有的K线都缩在一个高度上，没有按照KlineMainView的高度去展开，我们现在的数据是160000+，看到的数据都在顶部，下半部分完全没用到，跟踪代码发现是把model转为positionModel时候有问题，正在你的计算方法，改完了我看能不能把代码贴出来吧

**Comment by renjiale1214** [comment]
找到问题了，Y_KlineMainView里的两行代码：maxAssert *= 1.0001; minAssert *= 0.9991;
这个放大缩小了当前屏幕中数据的最大最小值的上下限。在我们后台monk的数据不够真实的时候，就可能出现所有数据都挤在上半部分区域的问题。如果monk数据是几千，那么这个比例显示也不会有什么问题，但是一旦价格数据在100，000这个级别甚至是百万级别，小小的万分之一的差额也会被放大很多。

不知道作者这里为什么要写一个比例的放大和缩小吗

**Comment by iriswe** [comment]
请问这个K线图你最终怎么选型的。。。

**Comment by ghost** [comment]
> 找到问题了，Y_KlineMainView里的两行代码：maxAssert *= 1.0001; minAssert *= 0.9991;
> 这个放大缩小了当前屏幕中数据的最大最小值的上下限。在我们后台monk的数据不够真实的时候，就可能出现所有数据都挤在上半部分区域的问题。如果monk数据是几千，那么这个比例显示也不会有什么问题，但是一旦价格数据在100，000这个级别甚至是百万级别，小小的万分之一的差额也会被放大很多。
> 
> 不知道作者这里为什么要写一个比例的放大和缩小吗
l


兄弟你好，我也遇见了同意的问题，请问你当时是如何解决的呢？谢谢
