### ISSUE TITLE
内存消耗过大，能否解决/Memory consumption is too large, can be solved

### ISSUE THREAD

**Issue by Tanghaiwen** [yate1996/KLine#40]
你好，我现在用了你的这个类，功能是很不错，刚好满足了我们的需求，现在就是内存消耗过大，滑动时，内存溢出而闪退。能否给出个好的方案解决内存消耗过大。。非常感谢，
Hello, I have now used your class, which is very good and just meets our needs. Now, memory consumption is too high. Can you come up with a good solution for excessive memory consumption? Thank you very much.

**Comment by WillkYang** [comment]
你好，内存问题已经修复，谢谢支持🙏
