### ISSUE TITLE
Y_KLineModel 内存泄漏

### ISSUE THREAD

**Issue by xiaozhenyangCode** [yate1996/KLine#56]
- (NSNumber *)MA26
{
    if (!_MA26) {
        NSInteger index = [self.ParentGroupModel.models indexOfObject:self];
        if (index >= 25) {
            if (index > 25) {
                _MA26 = @((self.SumOfLastClose.floatValue - self.ParentGroupModel.models[index - 26].SumOfLastClose.floatValue) / 26);
            } else {
                _MA26 = @(self.SumOfLastClose.floatValue / 26);
            }
        }
    }
    return _MA26;
} 
类型与这些属性初始化都会有内存泄漏

**Comment by qq826075241** [comment]
请问内存泄漏的问题你是怎么解决的？

**Comment by xiaozhenyangCode** [comment]
把转换 Y_KLineModel 放在了Y_KLineGroupModel.m 里面

**Comment by qq826075241** [comment]
感谢回复，我是在Y_KLineGroupModel里加了copy方法，也解决了这个问题

**Comment by xiaozhenyangCode** [comment]
copy???

**Comment by qq826075241** [comment]
就是拷贝了Y_KLineGroupModel对象再赋到Y_KLineModel中处理，防止出现循环引用

**Comment by wiilsliang** [comment]
> copy???

能不能具体贴下代码？谢谢了

**Comment by wiilsliang** [comment]
> 就是拷贝了Y_KLineGroupModel对象再赋到Y_KLineModel中处理，防止出现循环引用

能不能贴下代码？谢谢了

**Comment by zhanghuanProgrammer** [comment]
/**
 *  前一个Model
 */
@property (nonatomic, strong) Y_KLineModel *PreviousKlineModel;

/**
 *  父ModelArray:用来给当前Model索引到Parent数组
 */
@property (nonatomic, strong) Y_KLineGroupModel *ParentGroupModel;


把上面的strong改成weak , 保证不会再内存泄漏,我找了3个小时才排除这个问题,作者在这里大意了,指向前一个model和父model,怎么能用strong了,这样导致互相引用,不能释放内存呀

**Comment by xinle13** [comment]
@property (nonatomic, copy) NSNumber *  这里的NSNumber的属性用strong吧,copy也会内存泄露

**Comment by WillkYang** [comment]
fixed.
